<?php

namespace Database\Seeders;

use App\Model\Backend\ItemMallItemCategories;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemMallItemCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        ItemMallItemCategories::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        ItemMallItemCategories::insert([
            //Garment
            [
                'TypeID2' => 1,
                'TypeID3' => 1,
                'category' => 'Garment',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 1,
                'category' => 'Garment',
                'TypeID4' => 2,
                'type' => 'Shoulder',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 1,
                'category' => 'Garment',
                'TypeID4' => 3,
                'type' => 'Chest',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 1,
                'category' => 'Garment',
                'TypeID4' => 4,
                'type' => 'Legs',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 1,
                'category' => 'Garment',
                'TypeID4' => 5,
                'type' => 'Glove',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 1,
                'category' => 'Garment',
                'TypeID4' => 6,
                'type' => 'Foot',
                'race' => 1,
            ],
            //Protector
            [
                'TypeID2' => 1,
                'TypeID3' => 2,
                'category' => 'Protector',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 2,
                'category' => 'Protector',
                'TypeID4' => 2,
                'type' => 'Shoulder',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 2,
                'category' => 'Protector',
                'TypeID4' => 3,
                'type' => 'Chest',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 2,
                'category' => 'Protector',
                'TypeID4' => 4,
                'type' => 'Legs',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 2,
                'category' => 'Protector',
                'TypeID4' => 5,
                'type' => 'Glove',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 2,
                'category' => 'Protector',
                'TypeID4' => 6,
                'type' => 'Foot',
                'race' => 1,
            ],
            //Armor
            [
                'TypeID2' => 1,
                'TypeID3' => 3,
                'category' => 'Armor',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 3,
                'category' => 'Armor',
                'TypeID4' => 2,
                'type' => 'Shoulder',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 3,
                'category' => 'Armor',
                'TypeID4' => 3,
                'type' => 'Chest',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 3,
                'category' => 'Armor',
                'TypeID4' => 4,
                'type' => 'Legs',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 3,
                'category' => 'Armor',
                'TypeID4' => 5,
                'type' => 'Glove',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 3,
                'category' => 'Armor',
                'TypeID4' => 6,
                'type' => 'Foot',
                'race' => 1,
            ],
            //Shields
            [
                'TypeID2' => 1,
                'TypeID3' => 4,
                'category' => 'Shield',
                'TypeID4' => 1,
                'type' => 'Shield',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 4,
                'category' => 'Shield',
                'TypeID4' => 2,
                'type' => 'Shield',
                'race' => 2,
            ],
            //Chinese Accessory
            [
                'TypeID2' => 1,
                'TypeID3' => 5,
                'category' => 'Accessory',
                'TypeID4' => 1,
                'type' => 'Earring',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 5,
                'category' => 'Accessory',
                'TypeID4' => 2,
                'type' => 'Necklace',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 5,
                'category' => 'Accessory',
                'TypeID4' => 3,
                'type' => 'Ring',
                'race' => 1,
            ],
            //Chinese Weapons
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 2,
                'type' => 'Sword',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 3,
                'type' => 'Blade',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 4,
                'type' => 'Spear',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 5,
                'type' => 'Glaive',
                'race' => 1,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 6,
                'type' => 'Bow',
                'race' => 1,
            ],
            //European Weapons
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 7,
                'type' => 'One Handed Sword',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 8,
                'type' => 'Two Handed Sword',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 9,
                'type' => 'Axe',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 10,
                'type' => 'Warlock Rod',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 11,
                'type' => 'Staff',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 12,
                'type' => 'Crossbow',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 13,
                'type' => 'Dagger',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 14,
                'type' => 'Bard',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 6,
                'category' => 'Weapon',
                'TypeID4' => 15,
                'type' => 'Cleric Rod',
                'race' => 2,
            ],
            //Robe
            [
                'TypeID2' => 1,
                'TypeID3' => 9,
                'category' => 'Robe',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 9,
                'category' => 'Robe',
                'TypeID4' => 2,
                'type' => 'Shoulder',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 9,
                'category' => 'Robe',
                'TypeID4' => 3,
                'type' => 'Chest',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 9,
                'category' => 'Robe',
                'TypeID4' => 4,
                'type' => 'Legs',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 9,
                'category' => 'Robe',
                'TypeID4' => 5,
                'type' => 'Glove',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 9,
                'category' => 'Robe',
                'TypeID4' => 6,
                'type' => 'Foot',
                'race' => 2,
            ],
            //Protector
            [
                'TypeID2' => 1,
                'TypeID3' => 10,
                'category' => 'Light Armor',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 10,
                'category' => 'Light Armor',
                'TypeID4' => 2,
                'type' => 'Shoulder',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 10,
                'category' => 'Light Armor',
                'TypeID4' => 3,
                'type' => 'Chest',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 10,
                'category' => 'Light Armor',
                'TypeID4' => 4,
                'type' => 'Legs',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 10,
                'category' => 'Light Armor',
                'TypeID4' => 5,
                'type' => 'Glove',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 10,
                'category' => 'Light Armor',
                'TypeID4' => 6,
                'type' => 'Foot',
                'race' => 2,
            ],
            //Armor
            [
                'TypeID2' => 1,
                'TypeID3' => 11,
                'category' => 'Heavy Armor',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 11,
                'category' => 'Heavy Armor',
                'TypeID4' => 2,
                'type' => 'Shoulder',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 11,
                'category' => 'Heavy Armor',
                'TypeID4' => 3,
                'type' => 'Chest',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 11,
                'category' => 'Heavy Armor',
                'TypeID4' => 4,
                'type' => 'Legs',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 11,
                'category' => 'Heavy Armor',
                'TypeID4' => 5,
                'type' => 'Glove',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 11,
                'category' => 'Heavy Armor',
                'TypeID4' => 6,
                'type' => 'Foot',
                'race' => 2,
            ],
            //European Accessory
            [
                'TypeID2' => 1,
                'TypeID3' => 12,
                'category' => 'Accessory',
                'TypeID4' => 1,
                'type' => 'Earring',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 12,
                'category' => 'Accessory',
                'TypeID4' => 2,
                'type' => 'Necklace',
                'race' => 2,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 12,
                'category' => 'Accessory',
                'TypeID4' => 3,
                'type' => 'Ring',
                'race' => 2,
            ],
            //Avatars
            [
                'TypeID2' => 1,
                'TypeID3' => 13,
                'category' => 'Avatars',
                'TypeID4' => 1,
                'type' => 'Hat',
                'race' => 0,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 13,
                'category' => 'Avatars',
                'TypeID4' => 2,
                'type' => 'Dress',
                'race' => 0,
            ],
            [
                'TypeID2' => 1,
                'TypeID3' => 13,
                'category' => 'Avatars',
                'TypeID4' => 3,
                'type' => 'Accessory',
                'race' => 0,
            ],
            //Devil Spirits
            [
                'TypeID2' => 1,
                'TypeID3' => 14,
                'category' => 'Devil Spirits',
                'TypeID4' => 1,
                'type' => 'Devil',
                'race' => 0,
            ],
            //Scrolls
            [
                'TypeID2' => 3,
                'TypeID3' => 3,
                'category' => 'Scrolls',
                'TypeID4' => 3,
                'type' => 'Reverse Return Scroll',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 3,
                'category' => 'Scrolls',
                'TypeID4' => 5,
                'type' => 'Global Chatting',
                'race' => 0,
            ],
            //Coins
            [
                'TypeID2' => 3,
                'TypeID3' => 5,
                'category' => 'Coins',
                'TypeID4' => 1,
                'type' => 'Coins',
                'race' => 0,
            ],
            //Elixirs
            [
                'TypeID2' => 3,
                'TypeID3' => 10,
                'category' => 'Elixirs',
                'TypeID4' => 1,
                'type' => 'Elixirs',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 10,
                'category' => 'Elixirs',
                'TypeID4' => 2,
                'type' => 'Lucky Powder',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 10,
                'category' => 'Elixirs',
                'TypeID4' => 4,
                'type' => 'Advanced Elixir',
                'race' => 0,
            ],
            //Stones
            [
                'TypeID2' => 3,
                'TypeID3' => 11,
                'category' => 'Stones',
                'TypeID4' => 1,
                'type' => 'Magic Stones',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 11,
                'category' => 'Stones',
                'TypeID4' => 2,
                'type' => 'Attribute Stones',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 11,
                'category' => 'Stones',
                'TypeID4' => 7,
                'type' => 'Alchemy Stones',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 11,
                'category' => 'Stones',
                'TypeID4' => 8,
                'type' => 'Socket Stones',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 11,
                'category' => 'Stones',
                'TypeID4' => 9,
                'type' => 'Destruction Rondo',
                'race' => 0,
            ],
            [
                'TypeID2' => 3,
                'TypeID3' => 11,
                'category' => 'Stones',
                'TypeID4' => 10,
                'type' => 'Magic Stone of Sockets',
                'race' => 0,
            ],
            //Dimension Hole Stones
            [
                'TypeID2' => 3,
                'TypeID3' => 12,
                'category' => 'Dimension Hole',
                'TypeID4' => 7,
                'type' => 'Dimension Hole',
                'race' => 0,
            ],
            //ETC
            [
                'TypeID2' => 3,
                'TypeID3' => 13,
                'category' => 'ETC',
                'TypeID4' => 0,
                'type' => 'ETC',
                'race' => 0,
            ],
            //Pets
            [
                'TypeID2' => 2,
                'TypeID3' => 1,
                'category' => 'Pets',
                'TypeID4' => 1,
                'type' => 'Pets',
                'race' => 0,
            ],
            [
                'TypeID2' => 2,
                'TypeID3' => 1,
                'category' => 'Pets',
                'TypeID4' => 2,
                'type' => 'Pets',
                'race' => 0,
            ],
        ]);
    }
}
